// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TryingtogetSaveChangestowork : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TryingtogetSaveChangestowork));
        
        string IMigrationMetadata.Id
        {
            get { return "201708230648403_Trying to get SaveChanges to work"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
