// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Assetcontainsswitch : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Assetcontainsswitch));
        
        string IMigrationMetadata.Id
        {
            get { return "201709080717514_Asset contains switch"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
