// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addedamanufacturertotheentity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addedamanufacturertotheentity));
        
        string IMigrationMetadata.Id
        {
            get { return "201710060837582_Added a manufacturer to the entity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
