// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class lanandfirewalladded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(lanandfirewalladded));
        
        string IMigrationMetadata.Id
        {
            get { return "201709211043563_lan and firewall added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
